---
engines:
  csslint:
    enabled: true
    checks:
      compatible-vendor-prefixes:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
  - "src/font-awesome-4.5.0/**/*"
