os:
  - linux
  - osx
osx_image: xcode8
sudo: false

language: node_js
node_js:
  - "6"
  - "5"
  - "4"

addons:
  apt:
    packages:
      - wine

cache:
  - apt: true
  - directories:
    - "$HOME/.npm"
    - "$HOME/.electron"

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1
  - npm install

script:
  - npm run build
