os:
  - linux
#   - osx
# osx_image: xcode8
sudo: false

language: node_js
node_js:
  - "6"
  - "5"
  - "4"

addons:
  apt:
    packages:
      - wine

cache:
  - apt: true
  - directories:
    - "$HOME/.npm"
    - "$HOME/.electron"

install:
  - npm install

# https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - npm run build
