language: node_js
node_js:
  - "6"
  - "5"
  - "4"

sudo: false

addons:
  apt:
    packages:
      - wine

install:
  - npm install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3" # give xvfb some time to start

script:
  - npm run build
